services:
  - type: web
    name: orinowo-musicgen-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: HF_API_KEY
        sync: false
