name: Smoke test live endpoints

on:
  workflow_dispatch:
    inputs:
      site:
        description: "Public site URL (e.g., https://orinowo-next-2025.vercel.app)"
        required: true
        type: string
  deployment_status:

jobs:
  smoke:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci || npm install

      - name: Run smoke tests
        env:
          PUBLIC_SITE_URL: ${{ github.event.inputs.site || secrets.PUBLIC_SITE_URL }}
        run: |
          if [ -z "$PUBLIC_SITE_URL" ]; then
            echo "PUBLIC_SITE_URL not provided. Set workflow input 'site' or repo secret 'PUBLIC_SITE_URL'." >&2
            exit 1
          fi
          npm run smoke
